services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis-server
    networks:
      - backend
    restart: always

  mongodb:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: always

  redis-server:
    image: redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: always

  mongodb-backup:
    build:
      context: ./backup
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    depends_on:
      - mongodb
    networks:
      - backend
    restart: always

  https-portal:
    image: steveltn/https-portal
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    networks:
      - backend
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: |
        api.battle-llm.io -> http://app:9000
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'
    
volumes:
  mongo_data:
  redis_data:
  https-portal-data:  

networks:
  backend:
    driver: bridge
